version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatbot-ai:local
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
